export const dummy_data={
  "products" :
    {
      "phones" : [
        {
          "id": "kzp0en6knn",
          "addDate" : "21-06-2017",
          "name": "Moto",
          "price" : "3999",
          "imageUrl" : "https://images-na.ssl-images-amazon.com/images/I/41ddMNyQe6L.jpg",
          "color":"black",
          "ram":"4",
          "rom":"32",
          "processor":"Qualcomm Snapdragon 720G Processor",
          "operatingSystem":"Android 10",
          "battery":"5000",
          "frontCamera":"5",
          "rearCamera":"16",
          "displaySize":"6.54",
          "warrenty":"1",
          "modelName":"Z2",
          "modelNumber":"33611xg",
          "qty":"10"
        },
        {
          "id": "699mutjv45",
          "date" : "01-05-2018",
          "name": "Iphone",
          "price" : "12999",
          "imageUrl" : "https://www.t-mobile.com/content/dam/t-mobile/en-p/cell-phones/apple/apple-iphone-x/space-gray/Apple-iPhoneX-SpaceGray-1-3x.jpg",
          "color":"white",
          "ram":"4",
          "rom":"32",
          "processor":"Qualcomm Snapdragon 720G Processor",
          "operatingSystem":"Android 10",
          "battery":"5000",
          "frontCamera":"5",
          "rearCamera":"16",
          "displaySize":"6.54",
          "warrenty":"1",
          "modelName":"X",
          "modelNumber":"33611xg",
          "qty":"20"
        },
        {
          "id": "l9v8cy2a8z",
          "date" : "12-08-2018",
          "name": "Samsung",
          "price" : "11999",
          "imageUrl" : "https://www.t-mobile.com/content/dam/t-mobile/en-p/cell-phones/samsung/samsung-galaxy-s9-plus/lilac-purple/Samsung-Galaxy-S9-Plus-Lilac-Purple-2-3x.jpg",
          "color":"blue",
          "ram":"4",
          "rom":"32",
          "processor":"Qualcomm Snapdragon 720G Processor",
          "operatingSystem":"Android 10",
          "battery":"5000",
          "frontCamera":"5",
          "rearCamera":"16",
          "displaySize":"6.54",
          "warrenty":"1",
          "modelName":"S9",
          "modelNumber":"33611xg",
          "qty":"120"
        },
        {
          "id": "0bsjehplb1",
          "date" : "11-01-2017",
          "name": "Nokia",
          "price" : "5999 ",
          "imageUrl" : "https://static.toiimg.com/photo/56420863/Nokia-6.jpg",
          "color":"black",
          "ram":"4",
          "rom":"32",
          "processor":"Qualcomm Snapdragon 720G Processor",
          "operatingSystem":"Android 10",
          "battery":"5000",
          "frontCamera":"5",
          "rearCamera":"16",
          "displaySize":"6.54",
          "warrenty":"1",
          "modelName":"6",
          "modelNumber":"33611xg",
          "qty":"26"
        },
        {
          "id": "cqiwhz6jq8",
          "date" : "11-08-2017",
          "name": "Lenovo",
          "price" : "8999",
          "imageUrl" : "https://www.91-img.com/pictures/lenovo-p2-3gb-ram-mobile-phone-large-1.jpg",
          "color":"black",
          "ram":"4",
          "rom":"32",
          "processor":"Qualcomm Snapdragon 720G Processor",
          "operatingSystem":"Android 10",
          "battery":"5000",
          "frontCamera":"5",
          "rearCamera":"16",
          "displaySize":"6.54",
          "warrenty":"1",
          "modelName":"P2",
          "modelNumber":"33611xg",
          "qty":"17"
        },
        {
          "id": "vaingspk0a",
          "date" : "10-08-2018",
          "name": "OnePlus",
          "price" : "8999",
          "imageUrl" : "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR8epN7B9RthX5vIlrKoWdQKshkFLmSMl0i95YA_H8q2PfhxcKsKjo&usqp=CAc",
          "color":"black",
          "ram":"4",
          "rom":"32",
          "processor":"Qualcomm Snapdragon 720G Processor",
          "operatingSystem":"Android 10",
          "battery":"5000",
          "frontCamera":"5",
          "rearCamera":"16",
          "displaySize":"6.54",
          "warrenty":"1",
          "modelName":"6T",
          "modelNumber":"33611xg",
          "qty":"152"
        }
      ]
    }
}